/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<number, bigint | number | string, bigint | number | string>;

export type Interval = string;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AlertPrefs {
  categories: Generated<string[]>;
  daily_cap: Generated<number>;
  email_digest: Generated<boolean>;
  enabled: Generated<boolean>;
  last_active_at: Timestamp | null;
  last_active_cell_r7: string | null;
  min_urgency: Generated<string>;
  quiet_end: string | null;
  quiet_start: string | null;
  ring: Generated<number>;
  serious_in_quiet: Generated<boolean>;
  use_active_area: Generated<boolean>;
  user_id: string;
}

export interface Appeals {
  body: string;
  created_at: Generated<Timestamp>;
  decided_at: Timestamp | null;
  decided_by: string | null;
  id: Generated<string>;
  moderation_action_id: Int8;
  status: Generated<string>;
  user_id: string;
}

export interface Blocks {
  blocked_id: string;
  blocker_id: string;
  created_at: Generated<Timestamp>;
  via_anonymous: Generated<boolean>;
}

export interface Comments {
  author_id: string;
  body: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  post_id: string;
  status: Generated<string>;
}

export interface Communities {
  cover_media_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  description: string | null;
  id: Generated<string>;
  name: string;
  rules: string | null;
  slug: string;
  status: Generated<string>;
  type: string;
}

export interface CommunityMembers {
  alerts: Generated<boolean>;
  community_id: string;
  joined_at: Generated<Timestamp>;
  role: Generated<string>;
  show_on_profile: Generated<boolean>;
  user_id: string;
}

export interface CommunityProblemShares {
  community_id: string;
  created_at: Generated<Timestamp>;
  problem_id: string;
  shared_by: string;
}

export interface CommunityRequests {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  reason: string | null;
  requester_id: string;
  status: Generated<string>;
  type: string;
}

export interface ConversationParticipants {
  conversation_id: string;
  identity_revealed_at: Timestamp | null;
  last_read_message_id: Int8 | null;
  muted: Generated<boolean>;
  user_id: string;
}

export interface Conversations {
  created_at: Generated<Timestamp>;
  help_offer_id: string;
  id: Generated<string>;
  problem_id: string;
  read_only_at: Timestamp | null;
}

export interface HelpOffers {
  accepted_at: Timestamp | null;
  claimed_solved_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  helper_id: string;
  id: Generated<string>;
  message: string | null;
  problem_id: string;
  resolved_at: Timestamp | null;
  status: Generated<string>;
}

export interface IdempotencyKeys {
  created_at: Generated<Timestamp>;
  key: string;
  request_hash: string;
  response: Json | null;
  status_code: number | null;
  user_id: string;
}

export interface IncidentAffected {
  created_at: Generated<Timestamp>;
  fixed_confirmed_at: Timestamp | null;
  incident_id: string;
  user_id: string;
}

export interface IncidentMerges {
  actor_id: string | null;
  confidence: number | null;
  created_at: Generated<Timestamp>;
  from_id: string;
  id: Generated<string>;
  into_id: string;
  merged_by: string;
  undone_at: Timestamp | null;
}

export interface Incidents {
  affected_count: Generated<number>;
  area_cell: string;
  area_res: number;
  category: string;
  cell_r6: string;
  cell_r7: string;
  cell_r8: string | null;
  center_lat: number;
  center_lng: number;
  closed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  kind: string;
  locality: string | null;
  max_urgency: string;
  merged_into_id: string | null;
  problem_count: Generated<number>;
  status: Generated<string>;
}

export interface JobLeases {
  job_name: string;
  locked_by: string;
  locked_until: Timestamp;
}

export interface KarmaEntries {
  amount: number;
  created_at: Generated<Timestamp>;
  help_offer_id: string | null;
  id: Generated<Int8>;
  problem_id: string | null;
  reason: string;
  reverses_entry_id: Int8 | null;
  source_user_id: string | null;
  user_id: string;
}

export interface LaunchAreaCells {
  cell_r7: string;
  district: string;
  launch_area_id: string;
}

export interface LaunchAreas {
  enabled: Generated<boolean>;
  flags: Generated<Json>;
  id: string;
  name: string;
  opened_at: Timestamp | null;
}

export interface LocalityCache {
  cell: string;
  fetched_at: Generated<Timestamp>;
  locality: string;
}

export interface Media {
  blurhash: string | null;
  bytes: number;
  content_type: string;
  created_at: Generated<Timestamp>;
  height: number | null;
  id: Generated<string>;
  owner_id: string;
  processed_at: Timestamp | null;
  purpose: string;
  status: Generated<string>;
  storage_prefix: string | null;
  width: number | null;
}

export interface Messages {
  body: string | null;
  conversation_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  location_lat: number | null;
  location_lng: number | null;
  media_id: string | null;
  purge_after: Timestamp | null;
  sender_id: string | null;
  status: Generated<string>;
  type: string;
}

export interface MetricsLiquidityByDistrict {
  district: string | null;
  liquidity_pct: Numeric | null;
  problems: Int8 | null;
  week: Timestamp | null;
}

export interface MetricsLiquidityDaily {
  day: Timestamp | null;
  launch_area_id: string | null;
  liquidity_pct: Numeric | null;
  median_time_to_first_offer: Interval | null;
  offered_within_2h: Int8 | null;
  problems: Int8 | null;
}

export interface MetricsSolveRateWeekly {
  abandoned: Int8 | null;
  abandonment_rate_pct: Numeric | null;
  closed: Int8 | null;
  launch_area_id: string | null;
  solve_rate_pct: Numeric | null;
  solved: Int8 | null;
  week: Timestamp | null;
}

export interface ModerationActions {
  action: string;
  affected_user_id: string | null;
  automated: Generated<boolean>;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  moderator_id: string;
  reason: string;
  report_id: string | null;
  statement_of_reasons: string | null;
  target_id: string;
  target_type: string;
}

export interface Notifications {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  payload: Generated<Json>;
  pushed: Generated<boolean>;
  read_at: Timestamp | null;
  type: string;
  user_id: string;
}

export interface OtpChallenges {
  attempts: Generated<number>;
  channel: string;
  code_hash: string;
  consumed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  destination: string;
  expires_at: Timestamp;
  id: Generated<string>;
  purpose: string;
  user_id: string | null;
}

export interface OutboxDeliveries {
  consumer: string;
  delivered_at: Generated<Timestamp>;
  event_id: Int8;
}

export interface OutboxEvents {
  aggregate_id: string;
  aggregate_type: string;
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  last_error: string | null;
  next_attempt_at: Generated<Timestamp>;
  payload: Json;
  processed_at: Timestamp | null;
  status: Generated<string>;
  type: string;
}

export interface PostMedia {
  media_id: string;
  position: number;
  post_id: string;
}

export interface Posts {
  author_id: string;
  caption: string | null;
  cell_r7: string;
  community_id: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  kind: Generated<string>;
  problem_id: string | null;
  status: Generated<string>;
}

export interface PostTags {
  created_at: Generated<Timestamp>;
  post_id: string;
  status: Generated<string>;
  user_id: string;
}

export interface ProblemPhotos {
  created_at: Generated<Timestamp>;
  media_id: string;
  position: number;
  problem_id: string;
  update_id: string | null;
}

export interface ProblemPrivateLocations {
  accuracy_m: number | null;
  lat: number;
  lng: number;
  problem_id: string;
  purge_after: Timestamp | null;
}

export interface Problems {
  area_cell: string;
  area_res: number;
  category: string;
  cell_r6: string;
  cell_r7: string;
  cell_r8: string | null;
  center_lat: number;
  center_lng: number;
  closed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  credit_deadline: Timestamp | null;
  description: Generated<string>;
  hidden_at: Timestamp | null;
  id: Generated<string>;
  incident_id: string;
  is_anonymous: Generated<boolean>;
  kind: string;
  language_needed: string | null;
  last_activity_at: Generated<Timestamp>;
  last_raiser_response_at: Timestamp | null;
  launch_area_id: string;
  max_life_at: Timestamp;
  owner_id: string;
  penalized_at: Timestamp | null;
  reminder_stage: Generated<number>;
  response_due_at: Timestamp | null;
  solved_at: Timestamp | null;
  solved_via: string | null;
  status: Generated<string>;
  title: string;
  urgency: string;
}

export interface ProblemUpdates {
  author_id: string;
  author_role: string;
  body: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  problem_id: string;
  progress_status: string;
  status: Generated<string>;
}

export interface Profiles {
  avatar_media_id: string | null;
  bio: string | null;
  display_name: string;
  home_cell_r7: string | null;
  is_newcomer: Generated<boolean>;
  karma_balance: Generated<number>;
  languages: Generated<string[]>;
  neighbours_helped: Generated<number>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface PushSubscriptions {
  created_at: Generated<Timestamp>;
  endpoint: string;
  id: Generated<string>;
  keys: Json | null;
  kind: string;
  last_seen_at: Generated<Timestamp>;
  user_agent: string | null;
  user_id: string;
}

export interface RateLimitCounters {
  action: string;
  count: Generated<number>;
  user_id: string;
  window_start: Timestamp;
}

export interface RateLimitKeys {
  action: string;
  count: Generated<number>;
  key: string;
  window_start: Timestamp;
}

export interface Reactions {
  created_at: Generated<Timestamp>;
  post_id: string;
  user_id: string;
}

export interface Reports {
  created_at: Generated<Timestamp>;
  details: string | null;
  id: Generated<string>;
  reason: string;
  reporter_id: string;
  resolved_at: Timestamp | null;
  resolved_by: string | null;
  status: Generated<string>;
  target_id: string;
  target_type: string;
}

export interface ServerKeys {
  created_at: Generated<Timestamp>;
  name: string;
  value: Json;
}

export interface Sessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  last_used_at: Generated<Timestamp>;
  mfa_verified_at: Timestamp | null;
  refresh_token_hash: string;
  revoked_at: Timestamp | null;
  user_agent: string | null;
  user_id: string;
}

export interface Users {
  adult_confirmed_at: Timestamp | null;
  anonymous_banned_until: Timestamp | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  email: string | null;
  email_verified_at: Timestamp | null;
  guidelines_accepted_at: Timestamp | null;
  id: Generated<string>;
  last_seen_at: Timestamp | null;
  on_notice_until: Timestamp | null;
  onboarded_at: Timestamp | null;
  password_hash: string | null;
  phone_e164: string | null;
  phone_verified_at: Timestamp | null;
  role: Generated<string>;
  status: Generated<string>;
}

export interface UserTotp {
  created_at: Generated<Timestamp>;
  enabled_at: Timestamp | null;
  secret: string;
  user_id: string;
}

export interface DB {
  alert_prefs: AlertPrefs;
  appeals: Appeals;
  blocks: Blocks;
  comments: Comments;
  communities: Communities;
  community_members: CommunityMembers;
  community_problem_shares: CommunityProblemShares;
  community_requests: CommunityRequests;
  conversation_participants: ConversationParticipants;
  conversations: Conversations;
  help_offers: HelpOffers;
  idempotency_keys: IdempotencyKeys;
  incident_affected: IncidentAffected;
  incident_merges: IncidentMerges;
  incidents: Incidents;
  job_leases: JobLeases;
  karma_entries: KarmaEntries;
  launch_area_cells: LaunchAreaCells;
  launch_areas: LaunchAreas;
  locality_cache: LocalityCache;
  media: Media;
  messages: Messages;
  metrics_liquidity_by_district: MetricsLiquidityByDistrict;
  metrics_liquidity_daily: MetricsLiquidityDaily;
  metrics_solve_rate_weekly: MetricsSolveRateWeekly;
  moderation_actions: ModerationActions;
  notifications: Notifications;
  otp_challenges: OtpChallenges;
  outbox_deliveries: OutboxDeliveries;
  outbox_events: OutboxEvents;
  post_media: PostMedia;
  post_tags: PostTags;
  posts: Posts;
  problem_photos: ProblemPhotos;
  problem_private_locations: ProblemPrivateLocations;
  problem_updates: ProblemUpdates;
  problems: Problems;
  profiles: Profiles;
  push_subscriptions: PushSubscriptions;
  rate_limit_counters: RateLimitCounters;
  rate_limit_keys: RateLimitKeys;
  reactions: Reactions;
  reports: Reports;
  server_keys: ServerKeys;
  sessions: Sessions;
  user_totp: UserTotp;
  users: Users;
}
