/**
 * Generates migrations/0003_budapest_launch_area.sql: every res-7 H3 cell of Budapest, tagged
 * with its district (ADR-024, L-10).
 *
 * District tagging is approximate: each cell goes to the district whose centre is nearest
 * relative to the district's size, and cells far from every district are outside the city. Good
 * enough for the launch-area check and per-district metrics; replace with official boundaries
 * before launch.
 */
import { writeFileSync } from 'node:fs';
import { cellToLatLng, polygonToCells } from 'h3-js';

// [district, centre lat, centre lng, rough radius in km]
const DISTRICTS: [string, number, number, number][] = [
  ['I', 47.4995, 19.0335, 1.2], ['II', 47.539, 18.986, 3.5], ['III', 47.567, 19.039, 4.2], ['IV', 47.569, 19.088, 2.8],
  ['V', 47.5, 19.05, 1.1], ['VI', 47.507, 19.065, 1.0], ['VII', 47.5, 19.072, 1.0], ['VIII', 47.489, 19.086, 1.8],
  ['IX', 47.476, 19.09, 2.2], ['X', 47.482, 19.158, 3.2], ['XI', 47.458, 19.025, 3.8], ['XII', 47.499, 18.99, 3.3],
  ['XIII', 47.53, 19.07, 2.5], ['XIV', 47.52, 19.11, 2.5], ['XV', 47.56, 19.13, 3.0], ['XVI', 47.52, 19.19, 3.5],
  ['XVII', 47.48, 19.26, 4.5], ['XVIII', 47.43, 19.21, 4.5], ['XIX', 47.446, 19.145, 2.2], ['XX', 47.433, 19.115, 2.4],
  ['XXI', 47.42, 19.06, 4.0], ['XXII', 47.425, 19.01, 3.3], ['XXIII', 47.395, 19.115, 3.5],
];
const [W, S, E, N] = [18.925, 47.349, 19.335, 47.613];

function km(aLat: number, aLng: number, bLat: number, bLng: number) {
  const r = Math.PI / 180;
  const x = (bLng - aLng) * r * Math.cos(((aLat + bLat) / 2) * r);
  const y = (bLat - aLat) * r;
  return Math.sqrt(x * x + y * y) * 6371;
}

const cells = polygonToCells([[[S, W], [S, E], [N, E], [N, W], [S, W]]], 7);
const rows: string[] = [];
for (const cell of cells.sort()) {
  const [lat, lng] = cellToLatLng(cell);
  const nearest = DISTRICTS.map(([d, dl, dg, r]) => [d, km(lat, lng, dl, dg) / r, km(lat, lng, dl, dg)] as const).sort((a, b) => a[1] - b[1])[0]!;
  if (nearest[1] > 1.7 && nearest[2] > 4) continue;
  rows.push(`  ('budapest', '${cell}', '${nearest[0]}')`);
}

const sql = `-- Generated by packages/db/scripts/gen-budapest-cells.ts — do not edit by hand.
-- ADR-024: one launch area covering all of Budapest; each res-7 cell tagged with its district.
SET search_path = app, public;

INSERT INTO app.launch_areas (id, name, enabled, flags, opened_at)
VALUES ('budapest', 'Budapest', true, '{"feed_enabled": true, "issue_quorum_enabled": true}', now());

INSERT INTO app.launch_area_cells (launch_area_id, cell_r7, district) VALUES
${rows.join(',\n')};
`;
writeFileSync(new URL('../migrations/0003_budapest_launch_area.sql', import.meta.url), sql);
console.log(`${rows.length} cells`);
